source: org-id-cleanup.el
package: org-id-cleanup
required_pieces_commentary:
  - Purpose
  - Setup
pieces_for_docstring:
  - Purpose
testfile: oidclpt.el

# Maybe override this in rake_config_no_git.yml
rake_be_symlink: false
